name: Create Release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
      - name: Cache Kalkancrypt libraries
        id: kalkancrypt-cache
        uses: actions/cache@v3
        with:
          path: ./lib
          key: ${{ runner.os }}-kalkancrypt-libs-2
      - name: Install kalkan libraries
        if: steps.kalkancrypt-cache.outputs.cache-hit != 'true'
        env:
          KALKAN_CRYPT_URL: ${{ secrets.KALKAN_CRYPT_URL }}
          KALKAN_CRYPT_XMLDSIG_URL: ${{ secrets.KALKAN_CRYPT_XMLDSIG_URL }}
        run: |
          wget -P ./lib "$KALKAN_CRYPT_URL"
          wget -P ./lib "$KALKAN_CRYPT_XMLDSIG_URL"
      - name: Release version
        run: echo $GITHUB_REF_NAME
      - name: Build and Run tests
        run: ./gradlew -Pversion=$GITHUB_REF_NAME bootJar bootWar
      - uses: actions/upload-artifact@v3
        with:
          name: NCANode-build
          path: build/libs
          if-no-files-found: error
      - name: Create asset
        run: zip --junk-paths ./NCANode.zip build/libs/*.jar build/libs/*.war README.md LICENSE
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: NCANode v${{ github.ref_name }}
          draft: true
          prerelease: false
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./NCANode.zip
          asset_name: NCANode-${{ github.ref_name }}.zip
          asset_content_type: application/zip
